import { Noto_Sans_KR } from "next/font/google";
import Header from "./components/header/header";
import "./globals.css";

const geistSans = Noto_Sans_KR({
  weight: ["100", "300", "400", "500", "600", "700", "800"],
  variable: "--font-geist-sans",
  subsets: ["latin", "KR"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const response = await fetch("http://localhost:3000/api/users", {
    cache: "no-store",
  });
  const userProfile = await response.json();

  return (
    <html lang="ko">
      <body className={`${geistSans.variable}`}>
        <Header userProfile={userProfile} />
        <main>{children}</main>
      </body>
    </html>
  );
}
