import { Noto_Sans } from "next/font/google";
import Header from "./components/header/header";
import "./globals.css";
import { UserProvider } from "./context/userInfo";

const geistSans = Noto_Sans({
  weight: ["100", "300", "400", "500", "600", "700", "800"],
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const response = await fetch("http://localhost:3000/api/users", {
    cache: "no-store",
  });
  const userProfile = await response.json();

  return (
    <html lang="ko">
      <body className={`${geistSans.variable}`}>
        <UserProvider userProfile={userProfile}>
          <Header />
          <main>{children}</main>
        </UserProvider>
      </body>
    </html>
  );
}
